version: "3.9"
services:
    web:
        container_name: xwave-server
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        environment:
            - ASPNETCORE_URLS=https://+:5000;https://+:5001
            - ASPNETCORE_HTTPS_PORT=5000,5001

            # Use certificates from host machine
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}

            # Settings used at runtime
            - SeedData__Password=${SeedData__Password}
            - Jwt__Key=${Jwt__Key}
            - Jwt__Issuer=${Jwt__Issuer}
            - Jwt__Audience=${Jwt__Audience}
            - ConnectionStrings__DefaultDbLocation=${ConnectionStrings__DefaultDbLocation}
            - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
        volumes:
            - ~/.aspnet/https:/https:ro
            - ${LOCALAPPDATA}/XWave/docker:/app/log
        depends_on:
            - sqlserver
    sqlserver:
        ports:
            - "1433:1433"
        container_name: sqlserver
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: ${SqlServer__Password}
            ACCEPT_EULA: Y
            MSSQL_PID: Express
