version: "3.9"
services:
    web:
        container_name: xwave-server
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        environment:
            - ASPNETCORE_URLS=https://+:5000;https://+:5001
            - ASPNETCORE_HTTPS_PORT=5000,5001
            - ASPNETCORE_Kestrel__Certificates__Default__Password=xwave-cert
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/xwave-cert.pfx
        volumes:
            - ~/.aspnet/https:/https:ro
            - ${USERPROFILE}/.XWave/log:/app/log
        depends_on:
            - sqlserver
    sqlserver:
        ports: # not actually needed, because the two services are on the same network
            - "1433:1433" 
        container_name: sqlserver
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: XWave_db999
            ACCEPT_EULA: Y
            MSSQL_PID: Express
        