version: "3.9"
services:
    web:
        container_name: xwave-server
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        environment:
            - ASPNETCORE_URLS=http://+:5000;http://+:5001
            - ASPNETCORE_HTTP_PORT=5000,5001
        depends_on:
            - sqlserver
        # command: "dotnet dev-certs https --trust"
    sqlserver:
        ports: # not actually needed, because the two services are on the same network
            - "1433:1433" 
        container_name: sqlserver
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: XWave_db999
            ACCEPT_EULA: Y
            MSSQL_PID: Express
        